In [1]:
import numpy as np

## Creating ndarrays

In [3]:
data1 = [6, 7.5, 8, 0, 1]
type(data1)

list

In [4]:
data1

[6, 7.5, 8, 0, 1]

In [5]:
arr1 = np.array(data1)
type(arr1)

numpy.ndarray

In [6]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr2.size

8

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty((2,3,2))

array([[[1.14852575e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.75983079e+164]],

       [[7.73780546e-091, 2.35865824e+184],
        [4.31984045e-038, 8.69542908e-043],
        [3.99910963e+252, 4.11645687e+179]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

## Arithmetic with NumPy Arrays

In [23]:
# Vectorization

In [24]:
arr3 + arr3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
arr3 - arr3

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
arr3 * arr3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
arr3 / arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr3 / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [29]:
3 * arr3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [30]:
arr3 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr4 = np.array([[1, 3, 5], [7, 11, 13]])
arr4

array([[ 1,  3,  5],
       [ 7, 11, 13]])

In [33]:
# comparison two equal sized arrays using vectorization

In [34]:
arr3 > arr4

array([[False, False, False],
       [False, False, False]])

In [35]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr4 == arr3 

array([[ True, False, False],
       [False, False, False]])

## Basic Indexing and Slicing

In [38]:
# indexing on one dimensional array

In [39]:
numbers = np.arange(10)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
numbers[7]

7

In [41]:
numbers[5:]

array([5, 6, 7, 8, 9])

In [42]:
numbers[::2]

array([0, 2, 4, 6, 8])

In [43]:
numbers[0:3] = 0
numbers

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

In [44]:
numbers2 = np.array([[6,32,78], [86,5,75], [21, 4, 53]])
numbers2

array([[ 6, 32, 78],
       [86,  5, 75],
       [21,  4, 53]])

In [45]:
numbers2[0]

array([ 6, 32, 78])

In [46]:
numbers2[0, 2]

78

In [47]:
numbers2[0][2]

78

In [48]:
numbers3 = np.random.randint(10, size=(3,3,3))
numbers3

array([[[6, 6, 4],
        [3, 0, 0],
        [1, 7, 0]],

       [[6, 9, 6],
        [8, 7, 3],
        [3, 4, 7]],

       [[3, 7, 1],
        [7, 5, 4],
        [4, 5, 4]]])

In [49]:
numbers3[2, 0, 1]

7

In [50]:
numbers3[0, 0, 2]

4

In [51]:
numbers3[0, 2, 2]

0

In [52]:
numbers3[1, :, 2]

array([6, 3, 7])

In [53]:
numbers3[1, :, 2].shape

(3,)

In [54]:
numbers3[1, :, 2].ndim

1

In [55]:
numbers3[2, :, 1:2]

array([[7],
       [5],
       [5]])

In [56]:
numbers3[2, :, 1:2].shape

(3, 1)

In [57]:
numbers3[2, :, 1:2].ndim

2

## Boolean Indexing

In [59]:
names = np.array(["Doğukan", "Atakan", "Hazal Asu", "Ekinsu", "Berke Kaan", "Ece Dilara", "Yavuzhan", "Muhammed Ali", "Doğukan"])

In [60]:
names

array(['Doğukan', 'Atakan', 'Hazal Asu', 'Ekinsu', 'Berke Kaan',
       'Ece Dilara', 'Yavuzhan', 'Muhammed Ali', 'Doğukan'], dtype='<U12')

In [61]:
data = np.array([7,3,2,8,3,5,9,4,7])

In [62]:
data

array([7, 3, 2, 8, 3, 5, 9, 4, 7])

In [63]:
names == "Doğukan"

array([ True, False, False, False, False, False, False, False,  True])

In [64]:
data[names == "Doğukan"]

array([7, 7])

In [65]:
data[names == "Doğukan"][0]

7

In [66]:
names != "Doğukan"

array([False,  True,  True,  True,  True,  True,  True,  True, False])

In [67]:
data[names != "Doğukan"]

array([3, 2, 8, 3, 5, 9, 4])

In [68]:
data

array([7, 3, 2, 8, 3, 5, 9, 4, 7])

In [69]:
data[data < 5] = 0

In [70]:
data

array([7, 0, 0, 8, 0, 5, 9, 0, 7])

In [71]:
data[names == "Doğukan"]

array([7, 7])

In [72]:
data[names != "Doğukan"] = 13

In [73]:
data

array([ 7, 13, 13, 13, 13, 13, 13, 13,  7])

## Fancy Indexing

In [75]:
# fancy indexing allows us to use an array of indices to access multiple array elements at once.

In [76]:
array1 = np.random.randint(100, size=10)
array1

array([85, 38, 44, 26, 99, 65, 60, 93, 22,  1])

In [77]:
selected_elements = array1[[7, 2, 9]]
selected_elements

array([93, 44,  1])

In [78]:
# assigning new values using fancy indexing

In [79]:
array1

array([85, 38, 44, 26, 99, 65, 60, 93, 22,  1])

In [80]:
indices = [0, 1, 2]
new_values = [7, 7, 7]

In [81]:
array1[indices]

array([85, 38, 44])

In [82]:
array1[indices] = new_values
array1

array([ 7,  7,  7, 26, 99, 65, 60, 93, 22,  1])

In [83]:
# using fancy indexing on multi-dimensional arrays

In [84]:
array2 = np.random.randint(100, size=(3, 3))
array2

array([[68, 24, 79],
       [74, 55, 63],
       [13, 63, 65]])

In [85]:
row_indices = np.array([0,2])
row_indices

array([0, 2])

In [86]:
selected_rows = array2[row_indices, :]
selected_rows

array([[68, 24, 79],
       [13, 63, 65]])

## Transposing Arrays and Swapping Axes

In [88]:
# Transposing is a special form of reshaping that similarly returns a view on the underlying data.

In [89]:
array3 = np.arange(15).reshape((3,5))
array3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
array3.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Universal Functions: Fast Element-Wise Array Functions (uFuncs)

In [92]:
# They are functions that perform element-wise operations on data in ndarrays.

In [93]:
# some unary universal functions: abs, sqrt, square, exp, ceil, floor, isnan, etc.

In [94]:
myNumbers = np.array([0, -5, 3, -12, 7])
myNumbers

array([  0,  -5,   3, -12,   7])

In [189]:
myNumbers = np.abs(myNumbers)

In [191]:
np.sqrt(myNumbers)

array([0.        , 2.23606798, 1.73205081, 3.46410162, 2.64575131])

In [193]:
np.square(myNumbers)

array([  0,  25,   9, 144,  49])

In [203]:
# some binary universal functions: add, subtract, multiply, divide, floor_divide, maximum, minimum, greater, less, not_equal, etc.

In [205]:
np.add(myNumbers, 5)

array([ 5, 10,  8, 17, 12])

In [208]:
np.subtract(myNumbers, 2)

array([-2,  3,  1, 10,  5])

In [210]:
np.multiply(myNumbers, 10)

array([  0,  50,  30, 120,  70])

In [220]:
np.maximum(myNumbers, 5)

array([ 5,  5,  5, 12,  7])

## Array-Oriented Programming with Arrays

In [223]:
# expressing conditional logic as array operations

In [225]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [227]:
# suppose we wanted to take a value from x array whenever the corresponding value in cond is True, otherwise take the value from y array.

In [229]:
result = np.where(cond, x_arr, y_arr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [231]:
# the second and third arguments to numpy.where do not need to be arrays; one of them or both of them can be scalars.

In [233]:
# also, with numpy.where you can work with multidimensional arrays.

In [235]:
# a typical use of numpy.where in data analysis is to produce a new array of values based on another array. 

In [237]:
# For example, suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 2 and all negative values with -2.

In [243]:
arr = np.random.standard_normal((4,4))
arr

array([[-1.49837303, -1.39476523, -0.22077452, -1.76861493],
       [ 0.27760584,  0.33011752,  3.02358301,  0.61699754],
       [ 1.02156149,  2.03697741,  1.50278909,  0.66975453],
       [-0.01381532,  0.34769711,  0.36762448, -0.91734362]])

In [245]:
arr > 0

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False]])

In [247]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2,  2, -2]])

In [253]:
# you can combine scalars and arrays when using numpy.where 

In [255]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-1.49837303, -1.39476523, -0.22077452, -1.76861493],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.01381532,  2.        ,  2.        , -0.91734362]])

In [257]:
# mathematical and statistical methods

In [259]:
arr

array([[-1.49837303, -1.39476523, -0.22077452, -1.76861493],
       [ 0.27760584,  0.33011752,  3.02358301,  0.61699754],
       [ 1.02156149,  2.03697741,  1.50278909,  0.66975453],
       [-0.01381532,  0.34769711,  0.36762448, -0.91734362]])

In [261]:
arr.mean()

0.2738138358778457

In [263]:
np.mean(arr)

0.2738138358778457

In [265]:
arr.sum()

4.381021374045531

In [267]:
np.sum(arr)

4.381021374045531

In [273]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [275]:
arr2.mean()

4.5

In [277]:
arr2.mean(axis=1)

array([2.5, 6.5])

In [279]:
arr2.mean(axis=0)

array([3., 4., 5., 6.])

In [281]:
arr2.sum()

36

In [283]:
arr2.sum(axis=1)

array([10, 26])

In [285]:
arr2.sum(axis=0)

array([ 6,  8, 10, 12])

In [293]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
arr5.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [303]:
arr6 = np.random.randint(15, size=((3,3)))
arr6

array([[ 6,  9, 10],
       [ 0,  0, 11],
       [14,  2,  7]])

In [305]:
arr6.cumsum(axis=0)

array([[ 6,  9, 10],
       [ 6,  9, 21],
       [20, 11, 28]])

In [307]:
arr6.cumsum(axis=1)

array([[ 6, 15, 25],
       [ 0,  0, 11],
       [14, 16, 23]])

In [309]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [311]:
arr1.sum()

22.5

In [313]:
arr1.min()

0.0

In [315]:
arr1.max()

8.0

In [317]:
np.max(arr1)

8.0

In [319]:
np.std(arr1)

3.3466401061363023

In [321]:
np.var(arr1)

11.2

In [323]:
# methods for boolean arrays

In [325]:
# using sum method as a means of counting True values in a Boolean array.

In [327]:
arr7 = np.random.standard_normal(100)
arr7

array([ 1.31395985e-01, -9.64221352e-01,  6.36507800e-01, -1.59410262e-01,
       -1.01432026e+00,  2.28540583e-01, -8.24119277e-01,  1.61221810e+00,
       -3.58549221e-01,  3.83703885e-01,  2.72730142e-04,  7.13979781e-01,
        9.34934473e-01, -6.58611914e-01,  1.89944613e-01, -2.10162093e+00,
        1.20623984e+00, -1.07801499e+00, -5.69399746e-01,  7.85667719e-01,
       -2.56756575e-01,  8.89799073e-01,  1.09259635e+00, -7.11835728e-01,
       -1.08576125e+00,  8.53750574e-01, -6.35786999e-01,  9.59850144e-01,
        9.32268232e-01,  3.10088405e-01,  1.42387239e+00, -2.07087338e-01,
        8.74166772e-01,  9.23278442e-01,  1.23885374e+00, -8.61981310e-01,
        1.55902382e+00, -5.38877096e-01, -8.42741547e-01,  1.48120936e+00,
        1.22003824e+00, -1.86861736e-01, -1.94035669e+00, -6.87456585e-01,
       -1.31961375e+00,  2.93869185e-02,  4.81375713e-01,  3.30783494e-01,
       -2.37344344e-01, -7.65962600e-01,  9.16302224e-01, -2.99988460e-01,
       -9.68123129e-02, -

In [331]:
(arr7 > 0).sum() # number of positive values

52

In [333]:
(arr7 < 0).sum() # number of non-positive values

48

In [339]:
# any: checks whether one or more values in an array is True

In [341]:
bools = np.array([False, False, True, False])
bools.any()

True

In [343]:
# all: checks if every value is True

In [345]:
bools.all()

False

In [347]:
# These two methods above also work with non-Boolean arrays, where nonzero elements are treated as True.

## Sorting

In [370]:
arr8 = np.random.randint(100, size=10)
arr8

array([98, 58, 97, 85, 14, 10, 92, 20, 50, 66])

In [374]:
arr8.sort()
arr8

array([10, 14, 20, 50, 58, 66, 85, 92, 97, 98])

In [382]:
arr9 = np.random.randint(100, size=((5,3)))
arr9

array([[ 5, 68, 29],
       [43, 91, 24],
       [12, 33, 12],
       [58, 90, 66],
       [ 5, 58, 39]])

In [384]:
arr9.sort(axis=0)
arr9

array([[ 5, 33, 12],
       [ 5, 58, 24],
       [12, 68, 29],
       [43, 90, 39],
       [58, 91, 66]])

In [386]:
arr9.sort(axis=1)
arr9

array([[ 5, 12, 33],
       [ 5, 24, 58],
       [12, 29, 68],
       [39, 43, 90],
       [58, 66, 91]])

In [388]:
arr10  = np.array([5, -10, 7, 1, 0 -3])
arr10

array([  5, -10,   7,   1,  -3])

In [396]:
np.sort(arr10) # returns a sorted copy of an array instead of modifying the array in place.

array([-10,  -3,   1,   5,   7])

In [398]:
arr10

array([  5, -10,   7,   1,  -3])